name: 'Release'

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Use gradle cache for faster builds
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      - name: Build with Gradle
        env:
          MI_VERSION: ${{ github.event.release.tag_name }}
        run: ./gradlew build
      - name: Upload to Curseforge
        env:
          MI_VERSION: ${{ github.event.release.tag_name }}
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
        run: ./gradlew curseforge
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: modern-industrialization
          path: build/libs